if (ANDROID_ABI)
    set(NDK_DIR ${DEPS_DIR}/ndk)
    set(NDK_SRC ${NDK_DIR}/src)

    if (NOT ANDROID_NDK)
        GetProperty("version.ndk" NDK_VERSION)
        message(STATUS "android-ndk ${NDK_VERSION}")
        if (NOT EXISTS ${NDK_SRC})
            if (CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
                set(NDK_HOST_TAG linux)
            elseif (CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
                set(NDK_HOST_TAG darwin)
            elseif (CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
                set(NDK_HOST_TAG windows)
            else ()
                message(FATAL_ERROR "${CMAKE_HOST_SYSTEM_NAME} is not supported for Android build")
            endif ()
            DownloadProject(
                URL https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-${NDK_HOST_TAG}.zip
                DOWNLOAD_DIR ${NDK_DIR}/download
                SOURCE_DIR ${NDK_SRC}
            )
        endif ()
        GetProperty("version.sdk_compile" ANDROID_NATIVE_API_LEVEL)
    endif ()

    set(ANDROID_NATIVE_API_LEVEL    ${ANDROID_NATIVE_API_LEVEL})
    set(ANDROID_PLATFORM            ${ANDROID_NATIVE_API_LEVEL})
    set(ANDROID_STL                 none)
    set(ANDROID_CPP_FEATURES        exceptions rtti)
    set(CMAKE_ANDROID_EXCEPTIONS    ON)

    if (NOT ANDROID_NDK)
        set(ANDROID_NDK OFF)
    endif ()

    include(${NDK_SRC}/build/cmake/android.toolchain.cmake)
    set(ANDROID_CLANG_LIBRARY_FOLDER "${ANDROID_TOOLCHAIN_ROOT}/lib/clang/")
    file(GLOB _clang_root_dirs "${ANDROID_CLANG_LIBRARY_FOLDER}*")
    list(GET _clang_root_dirs 0 ANDROID_CLANG_LIBRARY_FOLDER)
    if (ANDROID_ABI STREQUAL "arm64-v8a")
        set(ARCH_NAME_ANDROID "aarch64")
    elseif (ANDROID_ABI STREQUAL "armeabi-v7a")
        set(ARCH_NAME_ANDROID "arm")
    elseif (ANDROID_ABI STREQUAL "x86_64")
        set(ARCH_NAME_ANDROID "x86_64")
    elseif (ANDROID_ABI STREQUAL "x86")
        set(ARCH_NAME_ANDROID "i686")
    else ()
        message(FATAL_ERROR "Unsupported Android ABI: ${ANDROID_ABI}")
    endif ()
    set(ANDROID_CLANG_LIBRARY_FOLDER "${ANDROID_CLANG_LIBRARY_FOLDER}/lib/linux/${ARCH_NAME_ANDROID}")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -L${ANDROID_CLANG_LIBRARY_FOLDER} -B${ANDROID_CLANG_LIBRARY_FOLDER}")
    set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}")

    file(GLOB NDK_RT_LIB "${ANDROID_TOOLCHAIN_ROOT}/lib/clang/*/lib/linux/libclang_rt.builtins-${ARCH_NAME_ANDROID}-android.a")
    if (NDK_RT_LIB)
        list(GET NDK_RT_LIB 0 NDK_RT_LIB)
        file(GLOB OWN_CLANG_DIRS "${DEPS_DIR}/clang/lib/clang/*")
        list(GET OWN_CLANG_DIRS 0 OWN_CLANG_DIR)
        get_filename_component(OWN_CLANG_VERSION "${OWN_CLANG_DIR}" NAME)
        set(OWN_CLANG_RT_DIR "${DEPS_DIR}/clang/lib/clang/${OWN_CLANG_VERSION}/lib/${ARCH_NAME_ANDROID}-none-linux-android${ANDROID_NATIVE_API_LEVEL}")
        if (NOT EXISTS ${OWN_CLANG_RT_DIR}/libclang_rt.builtins.a)
            file(MAKE_DIRECTORY ${OWN_CLANG_RT_DIR})
            file(COPY_FILE ${NDK_RT_LIB} ${OWN_CLANG_RT_DIR}/libclang_rt.builtins.a)
        endif ()
    endif ()
endif ()
